# Name of the site
site_name: Athene
site_author: zwangsheng

# Site theme
theme:
  name: material
  features:
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - content.action.view
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode


# Navigation
nav:
  - 'Home': index.md
  - 'BigData': 
    - 'Big Data': big-data/index.md
    - 'Spark': big-data/spark/index.md
    - 'Flink': big-data/flink/index.md
  - 'About me': about.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/zwangsheng
    - icon: fontawesome/solid/paper-plane
      link: mailto:<binjieyang@apache.com> 
markdown_extensions:
  - abbr
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true 
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - meta
